import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const retroFont = localFont({
  src: "./fonts/PressStart2P-vaV7.ttf",
  // variable: "--font-retro",
  weight: "100-900",
});

export const metadata: Metadata = {
  title: "Raziel Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${retroFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
